version: 0.0
os: linux

files:
  - source: target/app.jar
    destination: /opt/storeyes

hooks:
  BeforeInstall:
    - location: scripts/stop_app.sh
      timeout: 300
  AfterInstall:
    - location: scripts/start_app.sh
      timeout: 300
