version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - mvn clean package -DskipTests
      - mkdir -p backend
      - mv target/*.jar backend/app.jar
artifacts:
  files:
    - backend/app.jar
    - scripts/**
    - docker-compose.yml
    - mediamtx.yml